package com.ace.techfolio.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Persists a portfolio audit snapshot generated by the Gemini AI.
 *
 * <p>Each row captures the full AI analysis output alongside the
 * portfolio metrics at the time of the audit, enabling a historical
 * timeline view in the Audit History tab.</p>
 */
@Entity
@Table(name = "portfolio_audits")
public class PortfolioAudit {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private AppUser user;

    @NotNull
    @Column(name = "portfolio_value", precision = 19, scale = 4)
    private BigDecimal portfolioValue;

    @Size(max = 50)
    @Column(name = "investment_timeline", length = 50)
    private String investmentTimeline;

    @Size(max = 50)
    @Column(name = "risk_appetite", length = 50)
    private String riskAppetite;

    @Column(name = "overall_risk_score")
    private Integer overallRiskScore;

    /**
     * Full Gemini AI response stored as JSON text.
     * Contains concentration risks, savings warnings, diversification advice,
     * action items, and summary.
     */
    @Column(name = "ai_response", columnDefinition = "TEXT")
    private String aiResponse;

    @Column(name = "analyzed_at", nullable = false, updatable = false)
    private LocalDateTime analyzedAt;

    // =========================================================================
    // Lifecycle Callbacks
    // =========================================================================

    @PrePersist
    protected void onCreate() {
        this.analyzedAt = LocalDateTime.now();
    }

    // =========================================================================
    // Getters & Setters
    // =========================================================================

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public AppUser getUser() {
        return user;
    }

    public void setUser(AppUser user) {
        this.user = user;
    }

    public BigDecimal getPortfolioValue() {
        return portfolioValue;
    }

    public void setPortfolioValue(BigDecimal portfolioValue) {
        this.portfolioValue = portfolioValue;
    }

    public String getInvestmentTimeline() {
        return investmentTimeline;
    }

    public void setInvestmentTimeline(String investmentTimeline) {
        this.investmentTimeline = investmentTimeline;
    }

    public String getRiskAppetite() {
        return riskAppetite;
    }

    public void setRiskAppetite(String riskAppetite) {
        this.riskAppetite = riskAppetite;
    }

    public Integer getOverallRiskScore() {
        return overallRiskScore;
    }

    public void setOverallRiskScore(Integer overallRiskScore) {
        this.overallRiskScore = overallRiskScore;
    }

    public String getAiResponse() {
        return aiResponse;
    }

    public void setAiResponse(String aiResponse) {
        this.aiResponse = aiResponse;
    }

    public LocalDateTime getAnalyzedAt() {
        return analyzedAt;
    }
}
